### ISSUE TITLE
New spank_item S_JOB_ARRAY_ID and S_JOB_ARRAY_TASK_ID

### ISSUE THREAD

**Issue by maoliveirahpc** [stanford-rc/slurm-spank-lua#1]
Hi,

I've tried to add these two items to lua.c but keep getting:

error: spank: required plugin lua.so: init_post_opt() failed with rc=-1

I'm using Slurm 19.05.4.
Any chance of you having a look? Would be greatly appreciated.

Best Regards,

Miguel Oliveira

**Comment by kcgthb** [comment]
Hi Miguel,

It's hard to tell without seeing the actual code. Could please elaborate on what you're trying to achieve, and how you added those two items?

Also, I'm not the author of the plugin. As mentioned in the [`README`](/stanford-rc/slurm-spank-lua/blob/master/README.md), this repo is just a repackaging of the original Lua SPANK plugin for Slurm that has been originally developed at LLNL. So I'd recommend asking the question on the [LLNL Slurm SPANK plugins](https://github.com/grondo/slurm-spank-plugins) repo, where this plugin originates from.

Cheers!

**Comment by maoliveirahpc** [comment]
Hi,

Thank you for your reply. I am just trying to access S_JOB_ARRAY_ID and S_JOB_ARRAY_TASK_ID from a Lua plugin with spank:get_item. The only code changes I made were on lua.c:

a) Adding the two items between lines 129 and lines 130
b) the corresponding cases between lines 401 and 402

But you are right... I'll create an issue on the original code.

Thank,

 MAO
