### ISSUE TITLE
Add support for slurm_spank_log()

### ISSUE THREAD

**Issue by lukeyeager** [stanford-rc/slurm-spank-lua#16]
In 20.02.4, a new log function was added with https://github.com/SchedMD/slurm/commit/c600cddb618. It can be helpful to print from a SPANK plugin to the user without adding the `error:` prefix to the message.

**Comment by kcgthb** [comment]
Thanks for the suggestion @lukeyeager!

The v0.45 release now supports `slurm_spank_log()`.
