### ISSUE TITLE
Error in rpmbuild command 

### ISSUE THREAD

**Issue by whamblen** [stanford-rc/slurm-spank-lua#7]
Just a minor documentation tweak.  https://github.com/stanford-rc/slurm-spank-lua says to do 

$ rpmbuild -ta slurm-spank-lua-${VER}.tar.gz

but $VER from the previous steps evaluates to 'v0.43' and needs to be '0.43' to match the tar archive for the rpmbuild command.  I think you intended to do the same substitution with VAR in rpmbuild as with the wget command - namely.

$ rpmbuild -ta slurm-spank-lua-${VER//v}.tar.gz

**Comment by kcgthb** [comment]
Hi @whamblen, 
That's absolutely right! Thanks for reporting this, it should be fixed now.
